//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.BLLFactory
{
	using WHJ.MvcOA.IBLL;
	using WHJ.MvcOA.BLL;
    public partial class BLLSession:IBLLSession
    {   
    	private ICategoryBLL _CategoryBLL;
       public ICategoryBLL CategoryBLL 
       {
    		get
    		{
    			if(_CategoryBLL==null)
    			{
    				_CategoryBLL=new CategoryBLL();
    			}
    			return _CategoryBLL;
    		}  
       }
    
    	private IContentsBLL _ContentsBLL;
       public IContentsBLL ContentsBLL 
       {
    		get
    		{
    			if(_ContentsBLL==null)
    			{
    				_ContentsBLL=new ContentsBLL();
    			}
    			return _ContentsBLL;
    		}  
       }
    
    	private IDepartmentBLL _DepartmentBLL;
       public IDepartmentBLL DepartmentBLL 
       {
    		get
    		{
    			if(_DepartmentBLL==null)
    			{
    				_DepartmentBLL=new DepartmentBLL();
    			}
    			return _DepartmentBLL;
    		}  
       }
    
    	private IfeedbackBLL _feedbackBLL;
       public IfeedbackBLL feedbackBLL 
       {
    		get
    		{
    			if(_feedbackBLL==null)
    			{
    				_feedbackBLL=new feedbackBLL();
    			}
    			return _feedbackBLL;
    		}  
       }
    
    	private IMenusBLL _MenusBLL;
       public IMenusBLL MenusBLL 
       {
    		get
    		{
    			if(_MenusBLL==null)
    			{
    				_MenusBLL=new MenusBLL();
    			}
    			return _MenusBLL;
    		}  
       }
    
    	private INewsBLL _NewsBLL;
       public INewsBLL NewsBLL 
       {
    		get
    		{
    			if(_NewsBLL==null)
    			{
    				_NewsBLL=new NewsBLL();
    			}
    			return _NewsBLL;
    		}  
       }
    
    	private IPermissionBLL _PermissionBLL;
       public IPermissionBLL PermissionBLL 
       {
    		get
    		{
    			if(_PermissionBLL==null)
    			{
    				_PermissionBLL=new PermissionBLL();
    			}
    			return _PermissionBLL;
    		}  
       }
    
    	private IProductBLL _ProductBLL;
       public IProductBLL ProductBLL 
       {
    		get
    		{
    			if(_ProductBLL==null)
    			{
    				_ProductBLL=new ProductBLL();
    			}
    			return _ProductBLL;
    		}  
       }
    
    	private IRoleBLL _RoleBLL;
       public IRoleBLL RoleBLL 
       {
    		get
    		{
    			if(_RoleBLL==null)
    			{
    				_RoleBLL=new RoleBLL();
    			}
    			return _RoleBLL;
    		}  
       }
    
    	private IRolePermissionBLL _RolePermissionBLL;
       public IRolePermissionBLL RolePermissionBLL 
       {
    		get
    		{
    			if(_RolePermissionBLL==null)
    			{
    				_RolePermissionBLL=new RolePermissionBLL();
    			}
    			return _RolePermissionBLL;
    		}  
       }
    
    	private IsysdiagramsBLL _sysdiagramsBLL;
       public IsysdiagramsBLL sysdiagramsBLL 
       {
    		get
    		{
    			if(_sysdiagramsBLL==null)
    			{
    				_sysdiagramsBLL=new sysdiagramsBLL();
    			}
    			return _sysdiagramsBLL;
    		}  
       }
    
    	private IUserInfoBLL _UserInfoBLL;
       public IUserInfoBLL UserInfoBLL 
       {
    		get
    		{
    			if(_UserInfoBLL==null)
    			{
    				_UserInfoBLL=new UserInfoBLL();
    			}
    			return _UserInfoBLL;
    		}  
       }
    
    	private IUserRoleBLL _UserRoleBLL;
       public IUserRoleBLL UserRoleBLL 
       {
    		get
    		{
    			if(_UserRoleBLL==null)
    			{
    				_UserRoleBLL=new UserRoleBLL();
    			}
    			return _UserRoleBLL;
    		}  
       }
    
    	private IUserVipPermissionBLL _UserVipPermissionBLL;
       public IUserVipPermissionBLL UserVipPermissionBLL 
       {
    		get
    		{
    			if(_UserVipPermissionBLL==null)
    			{
    				_UserVipPermissionBLL=new UserVipPermissionBLL();
    			}
    			return _UserVipPermissionBLL;
    		}  
       }
    
    	private IW_WorkFlowBLL _W_WorkFlowBLL;
       public IW_WorkFlowBLL W_WorkFlowBLL 
       {
    		get
    		{
    			if(_W_WorkFlowBLL==null)
    			{
    				_W_WorkFlowBLL=new W_WorkFlowBLL();
    			}
    			return _W_WorkFlowBLL;
    		}  
       }
    
    	private IW_WorkFlowBranchBLL _W_WorkFlowBranchBLL;
       public IW_WorkFlowBranchBLL W_WorkFlowBranchBLL 
       {
    		get
    		{
    			if(_W_WorkFlowBranchBLL==null)
    			{
    				_W_WorkFlowBranchBLL=new W_WorkFlowBranchBLL();
    			}
    			return _W_WorkFlowBranchBLL;
    		}  
       }
    
    	private IW_WorkFlowNodeBLL _W_WorkFlowNodeBLL;
       public IW_WorkFlowNodeBLL W_WorkFlowNodeBLL 
       {
    		get
    		{
    			if(_W_WorkFlowNodeBLL==null)
    			{
    				_W_WorkFlowNodeBLL=new W_WorkFlowNodeBLL();
    			}
    			return _W_WorkFlowNodeBLL;
    		}  
       }
    
    	private IW_WorkNodeTypeBLL _W_WorkNodeTypeBLL;
       public IW_WorkNodeTypeBLL W_WorkNodeTypeBLL 
       {
    		get
    		{
    			if(_W_WorkNodeTypeBLL==null)
    			{
    				_W_WorkNodeTypeBLL=new W_WorkNodeTypeBLL();
    			}
    			return _W_WorkNodeTypeBLL;
    		}  
       }
    
    	private IW_WrokFlowRoleBLL _W_WrokFlowRoleBLL;
       public IW_WrokFlowRoleBLL W_WrokFlowRoleBLL 
       {
    		get
    		{
    			if(_W_WrokFlowRoleBLL==null)
    			{
    				_W_WrokFlowRoleBLL=new W_WrokFlowRoleBLL();
    			}
    			return _W_WrokFlowRoleBLL;
    		}  
       }
    
    	private IWR_WorkFlowApplyBLL _WR_WorkFlowApplyBLL;
       public IWR_WorkFlowApplyBLL WR_WorkFlowApplyBLL 
       {
    		get
    		{
    			if(_WR_WorkFlowApplyBLL==null)
    			{
    				_WR_WorkFlowApplyBLL=new WR_WorkFlowApplyBLL();
    			}
    			return _WR_WorkFlowApplyBLL;
    		}  
       }
    
    	private IWR_WrokFlowApplyDetailsBLL _WR_WrokFlowApplyDetailsBLL;
       public IWR_WrokFlowApplyDetailsBLL WR_WrokFlowApplyDetailsBLL 
       {
    		get
    		{
    			if(_WR_WrokFlowApplyDetailsBLL==null)
    			{
    				_WR_WrokFlowApplyDetailsBLL=new WR_WrokFlowApplyDetailsBLL();
    			}
    			return _WR_WrokFlowApplyDetailsBLL;
    		}  
       }
    
    }
}
