//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
    	public Model.Contents ToPOCO(){
    		return new Model.Contents(){
    			cnt_id=this.cnt_id,
    			cnt_title=this.cnt_title,
    			category_id=this.category_id,
    			cnt_content=this.cnt_content,
    			cnt_linkurl=this.cnt_linkurl,
    			cnt_imgurl=this.cnt_imgurl,
    			user_id=this.user_id,
    			cnt_is_lock=this.cnt_is_lock,
    			cnt_add_time=this.cnt_add_time,
    			cnt_exp1=this.cnt_exp1,
    			cnt_exp2=this.cnt_exp2,
    		};
    	}
    }
}
