//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
    	public Model.Department ToPOCO(){
    		return new Model.Department(){
    			dep_id=this.dep_id,
    			dep_pid=this.dep_pid,
    			dep_name=this.dep_name,
    			dep_remark=this.dep_remark,
    			dep_isdel=this.dep_isdel,
    			dep_addtime=this.dep_addtime,
    		};
    	}
    }
}
