//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
    	public Model.feedback ToPOCO(){
    		return new Model.feedback(){
    			f_id=this.f_id,
    			f_title=this.f_title,
    			f_content=this.f_content,
    			fuser_name=this.fuser_name,
    			fuser_tel=this.fuser_tel,
    			fuser_qq=this.fuser_qq,
    			fuser_email=this.fuser_email,
    			fadd_time=this.fadd_time,
    			freply_content=this.freply_content,
    			freply_time=this.freply_time,
    			is_lock=this.is_lock,
    		};
    	}
    }
}
