//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
    	public Model.News ToPOCO(){
    		return new Model.News(){
    			n_id=this.n_id,
    			category_id=this.category_id,
    			user_id=this.user_id,
    			n_title=this.n_title,
    			n_author=this.n_author,
    			n_form=this.n_form,
    			n_content=this.n_content,
    			n_sort_id=this.n_sort_id,
    			n_click=this.n_click,
    			n_is_lock=this.n_is_lock,
    			add_time=this.add_time,
    		};
    	}
    }
}
