//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
    	public Model.Permission ToPOCO(){
    		return new Model.Permission(){
    			p_id=this.p_id,
    			p_parent=this.p_parent,
    			p_name=this.p_name,
    			p_areaname=this.p_areaname,
    			p_controllername=this.p_controllername,
    			p_actionname=this.p_actionname,
    			p_formmethod=this.p_formmethod,
    			p_operationtype=this.p_operationtype,
    			p_ico=this.p_ico,
    			p_order=this.p_order,
    			p_islink=this.p_islink,
    			p_linkurl=this.p_linkurl,
    			p_isshow=this.p_isshow,
    			p_remark=this.p_remark,
    			p_iddel=this.p_iddel,
    			p_addtime=this.p_addtime,
    		};
    	}
    }
}
