//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
    	public Model.Role ToPOCO(){
    		return new Model.Role(){
    			r_id=this.r_id,
    			r_depid=this.r_depid,
    			r_name=this.r_name,
    			r_remark=this.r_remark,
    			r_isshow=this.r_isshow,
    			r_isdel=this.r_isdel,
    			r_addtime=this.r_addtime,
    		};
    	}
    }
}
