//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
    	public Model.RolePermission ToPOCO(){
    		return new Model.RolePermission(){
    			rp_id=this.rp_id,
    			rp_rid=this.rp_rid,
    			rp_pid=this.rp_pid,
    			rp_iddel=this.rp_iddel,
    			rp_addtime=this.rp_addtime,
    		};
    	}
    }
}
