//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
    	public Model.sysdiagrams ToPOCO(){
    		return new Model.sysdiagrams(){
    			name=this.name,
    			principal_id=this.principal_id,
    			diagram_id=this.diagram_id,
    			version=this.version,
    			definition=this.definition,
    		};
    	}
    }
}
