//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVipPermission
    {
    	public Model.UserVipPermission ToPOCO(){
    		return new Model.UserVipPermission(){
    			vip_id=this.vip_id,
    			vip_userid=this.vip_userid,
    			vip_permission=this.vip_permission,
    			vip_remark=this.vip_remark,
    			vip_iddel=this.vip_iddel,
    			vip_addtime=this.vip_addtime,
    		};
    	}
    }
}
