//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
    	public Model.UserRole ToPOCO(){
    		return new Model.UserRole(){
    			ur_id=this.ur_id,
    			ur_uid=this.ur_uid,
    			ur_rid=this.ur_rid,
    			ur_IsDel=this.ur_IsDel,
    			ur_addtime=this.ur_addtime,
    		};
    	}
    }
}
