//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WorkFlowBranch
    {
    	public Model.W_WorkFlowBranch ToPOCO(){
    		return new Model.W_WorkFlowBranch(){
    			wfb_Id=this.wfb_Id,
    			wfb_WnParentId=this.wfb_WnParentId,
    			wfb_Result=this.wfb_Result,
    			wfb_WnId=this.wfb_WnId,
    			wfb_IsDel=this.wfb_IsDel,
    			wfb_Addtime=this.wfb_Addtime,
    		};
    	}
    }
}
