//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WorkFlow
    {
    	public Model.W_WorkFlow ToPOCO(){
    		return new Model.W_WorkFlow(){
    			wf_Id=this.wf_Id,
    			wf_Name=this.wf_Name,
    			wf_Remark=this.wf_Remark,
    			wf_IsDel=this.wf_IsDel,
    			wf_Addtime=this.wf_Addtime,
    		};
    	}
    }
}
