//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WorkNodeType
    {
    	public Model.W_WorkNodeType ToPOCO(){
    		return new Model.W_WorkNodeType(){
    			wnt_id=this.wnt_id,
    			wnt_name=this.wnt_name,
    		};
    	}
    }
}
