//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WrokFlowRole
    {
    	public Model.W_WrokFlowRole ToPOCO(){
    		return new Model.W_WrokFlowRole(){
    			wfr_Id=this.wfr_Id,
    			wfr_WFNode=this.wfr_WFNode,
    			wfr_Role=this.wfr_Role,
    		};
    	}
    }
}
