//------------------------------------------------------------------------------
// <auto-generated>
// 为实体类 添加 ToPOCO 方法
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WorkFlowApply
    {
    	public Model.WR_WorkFlowApply ToPOCO(){
    		return new Model.WR_WorkFlowApply(){
    			wr_Id=this.wr_Id,
    			wr_UserId=this.wr_UserId,
    			wr_WFId=this.wr_WFId,
    			wf_CurWFNId=this.wf_CurWFNId,
    			wf_Title=this.wf_Title,
    			wf_Content=this.wf_Content,
    			wf_State=this.wf_State,
    			wf_TargetUserId=this.wf_TargetUserId,
    			wf_Priority=this.wf_Priority,
    			wf_IsDel=this.wf_IsDel,
    			wf_Addtime=this.wf_Addtime,
    		};
    	}
    }
}
