//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WHJ.MvcOA.Model;
    public partial class kyprintMVCEntities : DbContext
    {
        public kyprintMVCEntities()
            : base("name=kyprintMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<Contents> Contents { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<feedback> feedback { get; set; }
        public DbSet<Menus> Menus { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<RolePermission> RolePermission { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<UserVipPermission> UserVipPermission { get; set; }
        public DbSet<W_WorkFlow> W_WorkFlow { get; set; }
        public DbSet<W_WorkFlowBranch> W_WorkFlowBranch { get; set; }
        public DbSet<W_WorkFlowNode> W_WorkFlowNode { get; set; }
        public DbSet<W_WorkNodeType> W_WorkNodeType { get; set; }
        public DbSet<W_WrokFlowRole> W_WrokFlowRole { get; set; }
        public DbSet<WR_WorkFlowApply> WR_WorkFlowApply { get; set; }
        public DbSet<WR_WrokFlowApplyDetails> WR_WrokFlowApplyDetails { get; set; }
    }
}
