//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.BLL
{
    using WHJ.MvcOA.IBLL;
    using WHJ.MvcOA.Model;
    using WHJ.MvcOA.IDAL;
    public partial class DepartmentBLL:BaseBLL<Department>,IDepartmentBLL
    {
    	public override IBaseDAL<Department> SetCurrent()
        {
            return this.CreateDbSession.DepartmentDAL;
        }
    }
}
