//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated> 
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.IBLL
{
    public partial interface IBLLSession
    {   
        ICategoryBLL CategoryBLL {get;}
        IContentsBLL ContentsBLL {get;}
        IDepartmentBLL DepartmentBLL {get;}
        IfeedbackBLL feedbackBLL {get;}
        IMenusBLL MenusBLL {get;}
        INewsBLL NewsBLL {get;}
        IPermissionBLL PermissionBLL {get;}
        IProductBLL ProductBLL {get;}
        IRoleBLL RoleBLL {get;}
        IRolePermissionBLL RolePermissionBLL {get;}
        IsysdiagramsBLL sysdiagramsBLL {get;}
        IUserInfoBLL UserInfoBLL {get;}
        IUserRoleBLL UserRoleBLL {get;}
        IUserVipPermissionBLL UserVipPermissionBLL {get;}
        IW_WorkFlowBLL W_WorkFlowBLL {get;}
        IW_WorkFlowBranchBLL W_WorkFlowBranchBLL {get;}
        IW_WorkFlowNodeBLL W_WorkFlowNodeBLL {get;}
        IW_WorkNodeTypeBLL W_WorkNodeTypeBLL {get;}
        IW_WrokFlowRoleBLL W_WrokFlowRoleBLL {get;}
        IWR_WorkFlowApplyBLL WR_WorkFlowApplyBLL {get;}
        IWR_WrokFlowApplyDetailsBLL WR_WrokFlowApplyDetailsBLL {get;}
    }
}
