//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.DALFactory
{
	using WHJ.MvcOA.IDAL;
	using WHJ.MvcOA.DAL;
    public partial class DBSession:IDBSession
    {   
    	private ICategoryDAL _CategoryDAL;
       public ICategoryDAL CategoryDAL 
       {
    		get
    		{
    			if(_CategoryDAL==null)
    			{
    				_CategoryDAL=new CategoryDAL();
    			}
    			return _CategoryDAL;
    		}  
       }
    
    	private IContentsDAL _ContentsDAL;
       public IContentsDAL ContentsDAL 
       {
    		get
    		{
    			if(_ContentsDAL==null)
    			{
    				_ContentsDAL=new ContentsDAL();
    			}
    			return _ContentsDAL;
    		}  
       }
    
    	private IDepartmentDAL _DepartmentDAL;
       public IDepartmentDAL DepartmentDAL 
       {
    		get
    		{
    			if(_DepartmentDAL==null)
    			{
    				_DepartmentDAL=new DepartmentDAL();
    			}
    			return _DepartmentDAL;
    		}  
       }
    
    	private IfeedbackDAL _feedbackDAL;
       public IfeedbackDAL feedbackDAL 
       {
    		get
    		{
    			if(_feedbackDAL==null)
    			{
    				_feedbackDAL=new feedbackDAL();
    			}
    			return _feedbackDAL;
    		}  
       }
    
    	private IMenusDAL _MenusDAL;
       public IMenusDAL MenusDAL 
       {
    		get
    		{
    			if(_MenusDAL==null)
    			{
    				_MenusDAL=new MenusDAL();
    			}
    			return _MenusDAL;
    		}  
       }
    
    	private INewsDAL _NewsDAL;
       public INewsDAL NewsDAL 
       {
    		get
    		{
    			if(_NewsDAL==null)
    			{
    				_NewsDAL=new NewsDAL();
    			}
    			return _NewsDAL;
    		}  
       }
    
    	private IPermissionDAL _PermissionDAL;
       public IPermissionDAL PermissionDAL 
       {
    		get
    		{
    			if(_PermissionDAL==null)
    			{
    				_PermissionDAL=new PermissionDAL();
    			}
    			return _PermissionDAL;
    		}  
       }
    
    	private IProductDAL _ProductDAL;
       public IProductDAL ProductDAL 
       {
    		get
    		{
    			if(_ProductDAL==null)
    			{
    				_ProductDAL=new ProductDAL();
    			}
    			return _ProductDAL;
    		}  
       }
    
    	private IRoleDAL _RoleDAL;
       public IRoleDAL RoleDAL 
       {
    		get
    		{
    			if(_RoleDAL==null)
    			{
    				_RoleDAL=new RoleDAL();
    			}
    			return _RoleDAL;
    		}  
       }
    
    	private IRolePermissionDAL _RolePermissionDAL;
       public IRolePermissionDAL RolePermissionDAL 
       {
    		get
    		{
    			if(_RolePermissionDAL==null)
    			{
    				_RolePermissionDAL=new RolePermissionDAL();
    			}
    			return _RolePermissionDAL;
    		}  
       }
    
    	private IsysdiagramsDAL _sysdiagramsDAL;
       public IsysdiagramsDAL sysdiagramsDAL 
       {
    		get
    		{
    			if(_sysdiagramsDAL==null)
    			{
    				_sysdiagramsDAL=new sysdiagramsDAL();
    			}
    			return _sysdiagramsDAL;
    		}  
       }
    
    	private IUserInfoDAL _UserInfoDAL;
       public IUserInfoDAL UserInfoDAL 
       {
    		get
    		{
    			if(_UserInfoDAL==null)
    			{
    				_UserInfoDAL=new UserInfoDAL();
    			}
    			return _UserInfoDAL;
    		}  
       }
    
    	private IUserRoleDAL _UserRoleDAL;
       public IUserRoleDAL UserRoleDAL 
       {
    		get
    		{
    			if(_UserRoleDAL==null)
    			{
    				_UserRoleDAL=new UserRoleDAL();
    			}
    			return _UserRoleDAL;
    		}  
       }
    
    	private IUserVipPermissionDAL _UserVipPermissionDAL;
       public IUserVipPermissionDAL UserVipPermissionDAL 
       {
    		get
    		{
    			if(_UserVipPermissionDAL==null)
    			{
    				_UserVipPermissionDAL=new UserVipPermissionDAL();
    			}
    			return _UserVipPermissionDAL;
    		}  
       }
    
    	private IW_WorkFlowDAL _W_WorkFlowDAL;
       public IW_WorkFlowDAL W_WorkFlowDAL 
       {
    		get
    		{
    			if(_W_WorkFlowDAL==null)
    			{
    				_W_WorkFlowDAL=new W_WorkFlowDAL();
    			}
    			return _W_WorkFlowDAL;
    		}  
       }
    
    	private IW_WorkFlowBranchDAL _W_WorkFlowBranchDAL;
       public IW_WorkFlowBranchDAL W_WorkFlowBranchDAL 
       {
    		get
    		{
    			if(_W_WorkFlowBranchDAL==null)
    			{
    				_W_WorkFlowBranchDAL=new W_WorkFlowBranchDAL();
    			}
    			return _W_WorkFlowBranchDAL;
    		}  
       }
    
    	private IW_WorkFlowNodeDAL _W_WorkFlowNodeDAL;
       public IW_WorkFlowNodeDAL W_WorkFlowNodeDAL 
       {
    		get
    		{
    			if(_W_WorkFlowNodeDAL==null)
    			{
    				_W_WorkFlowNodeDAL=new W_WorkFlowNodeDAL();
    			}
    			return _W_WorkFlowNodeDAL;
    		}  
       }
    
    	private IW_WorkNodeTypeDAL _W_WorkNodeTypeDAL;
       public IW_WorkNodeTypeDAL W_WorkNodeTypeDAL 
       {
    		get
    		{
    			if(_W_WorkNodeTypeDAL==null)
    			{
    				_W_WorkNodeTypeDAL=new W_WorkNodeTypeDAL();
    			}
    			return _W_WorkNodeTypeDAL;
    		}  
       }
    
    	private IW_WrokFlowRoleDAL _W_WrokFlowRoleDAL;
       public IW_WrokFlowRoleDAL W_WrokFlowRoleDAL 
       {
    		get
    		{
    			if(_W_WrokFlowRoleDAL==null)
    			{
    				_W_WrokFlowRoleDAL=new W_WrokFlowRoleDAL();
    			}
    			return _W_WrokFlowRoleDAL;
    		}  
       }
    
    	private IWR_WorkFlowApplyDAL _WR_WorkFlowApplyDAL;
       public IWR_WorkFlowApplyDAL WR_WorkFlowApplyDAL 
       {
    		get
    		{
    			if(_WR_WorkFlowApplyDAL==null)
    			{
    				_WR_WorkFlowApplyDAL=new WR_WorkFlowApplyDAL();
    			}
    			return _WR_WorkFlowApplyDAL;
    		}  
       }
    
    	private IWR_WrokFlowApplyDetailsDAL _WR_WrokFlowApplyDetailsDAL;
       public IWR_WrokFlowApplyDetailsDAL WR_WrokFlowApplyDetailsDAL 
       {
    		get
    		{
    			if(_WR_WrokFlowApplyDetailsDAL==null)
    			{
    				_WR_WrokFlowApplyDetailsDAL=new WR_WrokFlowApplyDetailsDAL();
    			}
    			return _WR_WrokFlowApplyDetailsDAL;
    		}  
       }
    
    }
}
