//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.IDAL 
{
    public partial interface IDBSession
    {   
        ICategoryDAL CategoryDAL {get;}
        IContentsDAL ContentsDAL {get;}
        IDepartmentDAL DepartmentDAL {get;}
        IfeedbackDAL feedbackDAL {get;}
        IMenusDAL MenusDAL {get;}
        INewsDAL NewsDAL {get;}
        IPermissionDAL PermissionDAL {get;}
        IProductDAL ProductDAL {get;}
        IRoleDAL RoleDAL {get;}
        IRolePermissionDAL RolePermissionDAL {get;}
        IsysdiagramsDAL sysdiagramsDAL {get;}
        IUserInfoDAL UserInfoDAL {get;}
        IUserRoleDAL UserRoleDAL {get;}
        IUserVipPermissionDAL UserVipPermissionDAL {get;}
        IW_WorkFlowDAL W_WorkFlowDAL {get;}
        IW_WorkFlowBranchDAL W_WorkFlowBranchDAL {get;}
        IW_WorkFlowNodeDAL W_WorkFlowNodeDAL {get;}
        IW_WorkNodeTypeDAL W_WorkNodeTypeDAL {get;}
        IW_WrokFlowRoleDAL W_WrokFlowRoleDAL {get;}
        IWR_WorkFlowApplyDAL WR_WorkFlowApplyDAL {get;}
        IWR_WrokFlowApplyDetailsDAL WR_WrokFlowApplyDetailsDAL {get;}
    }
}
