//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RolePermission = new HashSet<RolePermission>();
            this.UserVipPermission = new HashSet<UserVipPermission>();
        }
    
        public int p_id { get; set; }
        public int p_parent { get; set; }
        public string p_name { get; set; }
        public string p_areaname { get; set; }
        public string p_controllername { get; set; }
        public string p_actionname { get; set; }
        public int p_formmethod { get; set; }
        public int p_operationtype { get; set; }
        public string p_ico { get; set; }
        public int p_order { get; set; }
        public bool p_islink { get; set; }
        public string p_linkurl { get; set; }
        public bool p_isshow { get; set; }
        public string p_remark { get; set; }
        public bool p_iddel { get; set; }
        public System.DateTime p_addtime { get; set; }
    
        public virtual ICollection<RolePermission> RolePermission { get; set; }
        public virtual ICollection<UserVipPermission> UserVipPermission { get; set; }
    }
}
