//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RolePermission = new HashSet<RolePermission>();
            this.UserRole = new HashSet<UserRole>();
            this.W_WrokFlowRole = new HashSet<W_WrokFlowRole>();
        }
    
        public int r_id { get; set; }
        public int r_depid { get; set; }
        public string r_name { get; set; }
        public string r_remark { get; set; }
        public bool r_isshow { get; set; }
        public bool r_isdel { get; set; }
        public System.DateTime r_addtime { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<RolePermission> RolePermission { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<W_WrokFlowRole> W_WrokFlowRole { get; set; }
    }
}
