//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int ur_id { get; set; }
        public int ur_uid { get; set; }
        public int ur_rid { get; set; }
        public bool ur_IsDel { get; set; }
        public System.DateTime ur_addtime { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
