//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Contents = new HashSet<Contents>();
            this.News = new HashSet<News>();
            this.UserRole = new HashSet<UserRole>();
            this.UserVipPermission = new HashSet<UserVipPermission>();
            this.WR_WorkFlowApply = new HashSet<WR_WorkFlowApply>();
            this.WR_WrokFlowApplyDetails = new HashSet<WR_WrokFlowApplyDetails>();
        }
    
        public int user_id { get; set; }
        public string u_name { get; set; }
        public string u_pwd { get; set; }
        public string real_name { get; set; }
        public string u_telephone { get; set; }
        public string u_email { get; set; }
        public bool u_is_lock { get; set; }
        public System.DateTime u_add_time { get; set; }
        public int u_depid { get; set; }
        public bool u_isdel { get; set; }
    
        public virtual ICollection<Contents> Contents { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<UserVipPermission> UserVipPermission { get; set; }
        public virtual ICollection<WR_WorkFlowApply> WR_WorkFlowApply { get; set; }
        public virtual ICollection<WR_WrokFlowApplyDetails> WR_WrokFlowApplyDetails { get; set; }
    }
}
