//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVipPermission
    {
        public int vip_id { get; set; }
        public int vip_userid { get; set; }
        public int vip_permission { get; set; }
        public string vip_remark { get; set; }
        public bool vip_iddel { get; set; }
        public System.DateTime vip_addtime { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
