//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WorkFlowNode
    {
        public W_WorkFlowNode()
        {
            this.W_WorkFlowBranch = new HashSet<W_WorkFlowBranch>();
            this.W_WorkFlowBranch1 = new HashSet<W_WorkFlowBranch>();
            this.W_WrokFlowRole = new HashSet<W_WrokFlowRole>();
            this.WR_WorkFlowApply = new HashSet<WR_WorkFlowApply>();
        }
    
        public int wn_Id { get; set; }
        public int wn_WorkFlowID { get; set; }
        public string wn_Name { get; set; }
        public Nullable<int> wn_PrevNode { get; set; }
        public Nullable<int> wn_NextNode { get; set; }
        public int wn_NodeType { get; set; }
        public int wn_NodeFuncType { get; set; }
        public string wn_NodeFuncClassName { get; set; }
        public int wn_Order { get; set; }
        public bool wn_IsDel { get; set; }
        public System.DateTime wn_Addtime { get; set; }
    
        public virtual W_WorkFlow W_WorkFlow { get; set; }
        public virtual ICollection<W_WorkFlowBranch> W_WorkFlowBranch { get; set; }
        public virtual ICollection<W_WorkFlowBranch> W_WorkFlowBranch1 { get; set; }
        public virtual W_WorkFlowNode NextNode { get; set; }
        public virtual W_WorkFlowNode PrevNode { get; set; }
        public virtual W_WorkNodeType W_WorkNodeType { get; set; }
        public virtual ICollection<W_WrokFlowRole> W_WrokFlowRole { get; set; }
        public virtual ICollection<WR_WorkFlowApply> WR_WorkFlowApply { get; set; }
    }
}
