//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHJ.MvcOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WorkFlowApply
    {
        public WR_WorkFlowApply()
        {
            this.WR_WrokFlowApplyDetails = new HashSet<WR_WrokFlowApplyDetails>();
        }
    
        public int wr_Id { get; set; }
        public int wr_UserId { get; set; }
        public int wr_WFId { get; set; }
        public int wf_CurWFNId { get; set; }
        public string wf_Title { get; set; }
        public string wf_Content { get; set; }
        public int wf_State { get; set; }
        public Nullable<int> wf_TargetUserId { get; set; }
        public int wf_Priority { get; set; }
        public bool wf_IsDel { get; set; }
        public System.DateTime wf_Addtime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual W_WorkFlow W_WorkFlow { get; set; }
        public virtual W_WorkFlowNode W_WorkFlowNode { get; set; }
        public virtual ICollection<WR_WrokFlowApplyDetails> WR_WrokFlowApplyDetails { get; set; }
    }
}
